Repository AI-Hypercomputer/xpk, pull requests merged in 2025-05, with the labels that each got.

#465 Add Multi-tier checkpointing support in XPK Cluster Creation
  src/xpk/commands/cluster.py
  src/xpk/core/mtc.py
  src/xpk/parser/cluster.py
  src/xpk/templates/mtc-cpc.yaml
  src/xpk/utils/kubectl.py
Labels: release-improvements, release-features

#468 Update README.md (Overview- what XPK is, when to use it)
  README.md
Labels: release-improvements

#472 Create xpk-slurm-commands.md
  xpk-slurm-commands.md
Labels: release-improvements

#471 Update README- added link to Slurm commands guide
  README.md
Labels: release-improvements

#469 Update installation section in README
  README.md
Labels: release-improvements

#475 Add Jobset controller patching for MTC cluster
  pytype-conf.cfg
  src/xpk/core/mtc.py
Labels: enhancement, release-features
