Repository AI-Hypercomputer/xpk, pull requests merged in 2025-04, with the labels that each got.

#441 fix: workloads not scheduling on A3 Ultra clusters
  src/xpk/core/workload_decorators/rdma_decorator.py
Labels: release-bugfix

#444 Disable creating additional networks for L4 and A2 clusters
  src/xpk/commands/cluster.py
  src/xpk/core/network.py
  src/xpk/core/nodepool.py
Labels: release-bugfix

#447 Add the option to use Multi-tier checkpointing in workloads
  src/xpk/core/docker_resources.py
  src/xpk/parser/workload.py
Labels: enhancement, release-features

#448 Integrate PathwaysJob into XPK.
  .github/workflows/reusable_workload_tests.yaml
  README.md
  src/xpk/commands/cluster.py
  src/xpk/commands/workload.py
  src/xpk/core/cluster.py
  src/xpk/core/docker_resources.py
  src/xpk/core/nap.py
  src/xpk/core/nodepool.py
  src/xpk/core/pathways.py
  src/xpk/core/scheduling.py
  src/xpk/parser/cluster.py
  src/xpk/parser/workload.py
Labels: enhancement, release-features

#449 Remove sidecar limits for GCS fuse storages
  src/xpk/commands/batch.py
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/commands/workload.py
  src/xpk/core/kjob.py
  src/xpk/core/storage.py
  src/xpk/core/workload_decorators/storage_decorator.py
Labels: release-improvements

#436 Implement Parallelstore and Hyperdisk storages attach
  README.md
  examples/storage/parallelstore-manifest-attach.yaml
  examples/storage/pd-manifest-attach.yaml
  src/xpk/commands/batch.py
  src/xpk/commands/cluster.py
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/cluster.py
  src/xpk/core/kjob.py
  src/xpk/core/network.py
  src/xpk/core/storage.py
  src/xpk/core/workload_decorators/storage_decorator.py
  src/xpk/parser/cluster.py
  src/xpk/parser/storage.py
Labels: release-features

#450 Add `--mount-options` parameter to `xpk storage attach/create`
  .github/workflows/reusable_storage_tests_by_type.yaml
  README.md
  src/xpk/commands/storage.py
  src/xpk/core/filestore.py
  src/xpk/core/gcsfuse.py
  src/xpk/parser/storage.py
Labels: release-features

#452 Fix `xpk workload create` for L4 and A100
  src/xpk/commands/workload.py
  src/xpk/core/storage.py
  src/xpk/core/workload.py
  src/xpk/templates/rxdm_container_a3high.yaml
  src/xpk/templates/rxdm_container_a3mega.yaml
Labels: release-bugfix

#453 Pre-populate GCS fuse metadata when mounting volumes
  .github/workflows/reusable_storage_tests_by_type.yaml
  README.md
  src/xpk/commands/storage.py
  src/xpk/core/gcsfuse.py
  src/xpk/parser/storage.py
Labels: release-improvements

#458 Merge main to develop
  README.md
  src/xpk/core/config.py
  src/xpk/parser/storage.py
  xpk-large-scale-guide.sh
Labels: release-bugfix

#459 GPUDirect-TCPX support for H100
  src/xpk/commands/cluster.py
  src/xpk/core/cluster.py
  src/xpk/core/kjob.py
  src/xpk/core/workload_decorators/tcpx_decorator.py
Labels: release-features

#456 Update pathways.py with worker component type.
  src/xpk/core/pathways.py
Labels: bug, release-bugfix

#460 README.md updates
  README.md
Labels: release-improvements

#457 Set network names based on cluster configuration when running workloads on A3 Mega, A3 Ultra and A4
  src/xpk/commands/kjob_common.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/kjob.py
  src/xpk/core/network.py
  src/xpk/core/workload_decorators/rdma_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-improvements

#463 Fix error when `xpk storage attach --type=gcpfilestore` without `--mount-options`
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_storage_create.yaml
  .github/workflows/reusable_storage_delete.yaml
  .github/workflows/reusable_storage_tests.yaml
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/filestore.py
Labels: release-bugfix

#464 Refactor parser/cluster.py
  src/xpk/parser/cluster.py
Labels: release-improvements
