Repository AI-Hypercomputer/xpk, pull requests merged in 2025-09, with the labels that each got.

#615 Add TAS support for workloads on DWS clusters
  src/xpk/commands/common.py
  src/xpk/commands/workload.py
  src/xpk/core/kueue.py
Labels: enhancement, release-features

#616 Fix tcpx_decorator
  src/xpk/core/workload_decorators/tcpx_decorator.py
  src/xpk/core/workload_decorators/tests/__init__.py
  src/xpk/core/workload_decorators/tests/unit/__init__.py
  src/xpk/core/workload_decorators/tests/unit/test_tcpx_decorator.py
  src/xpk/main.py
Labels: release-improvements

#622 Fix error when updating a cluster that already has JobSet
  src/xpk/core/cluster.py
Labels: release-bugfix

#628 refactor: make install-dev to include lint tools
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_unit_tests.yaml
  Makefile
Labels: release-improvements

#631 Don't set --enable-queued-provisioning for flex multislice
  src/xpk/core/capacity.py
Labels: release-bugfix

#637 Update .gitignore
  .gitignore
Labels: release-improvements

#635 Add golden tests to github actions
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_goldens.yaml
  goldens/NAP_cluster-create.txt
  goldens/NAP_cluster-create_with_pathways.txt
  src/xpk/commands/cluster.py
  src/xpk/commands/inspector.py
  src/xpk/commands/workload.py
  src/xpk/core/cluster.py
  src/xpk/core/commands.py
  src/xpk/core/docker_image.py
  src/xpk/core/jobset.py
  src/xpk/core/kjob.py
  src/xpk/core/kueue.py
  src/xpk/core/nap.py
  src/xpk/core/network.py
  src/xpk/core/nodepool.py
  src/xpk/core/pathways.py
  src/xpk/core/ray.py
  src/xpk/core/resources.py
  src/xpk/main.py
  src/xpk/utils/execution_context.py
  src/xpk/utils/file.py
Labels: release-improvements

#642 Simplify dependencies on build_test so it runs faster
  .github/workflows/build_tests.yaml
Labels: release-improvements

#641 Remove integration tests from feature branches
  .github/workflows/build_tests.yaml
  .github/workflows/nightly_tests.yaml
Labels: release-improvements

#652 Remove args from run_command_with_updates_retry
  src/xpk/commands/cluster.py
  src/xpk/commands/cluster_gcluster.py
  src/xpk/commands/common.py
  src/xpk/commands/job.py
  src/xpk/commands/kind.py
  src/xpk/commands/shell.py
  src/xpk/commands/workload.py
  src/xpk/core/capacity.py
  src/xpk/core/cluster.py
  src/xpk/core/cluster_private.py
  src/xpk/core/commands.py
  src/xpk/core/docker_image.py
  src/xpk/core/jobset.py
  src/xpk/core/kjob.py
  src/xpk/core/kueue.py
  src/xpk/core/nap.py
  src/xpk/core/network.py
  src/xpk/core/pathways.py
  src/xpk/core/ray.py
Labels: release-improvements

#657 Merge main to develop
  src/xpk/core/config.py
Labels: release-features

#659 Set gke_product_type:xpk cluster label
  goldens/Basic_cluster_create.txt
  goldens/Cluster_create_private.txt
  goldens/Cluster_create_with_gb200-4.txt
  goldens/NAP_cluster-create.txt
  goldens/NAP_cluster-create_with_pathways.txt
  src/xpk/commands/cluster.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/blueprint/testing/data/a3_mega.yaml
  src/xpk/core/blueprint/testing/data/a3_mega_spot.yaml
  src/xpk/core/blueprint/testing/data/a3_ultra.yaml
  src/xpk/core/blueprint/testing/data/a4.yaml
Labels: release-improvements

#661 Remove args from run_command_with_full_controls
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/core/commands.py
Labels: release-improvements

#663 Update supported platforms
  README.md
Labels: release-bugfix
