Repository AI-Hypercomputer/xpk, pull requests merged in 2025-06, with the labels that each got.

#487 Add codeowners for the Slice project
  .github/CODEOWNERS
Labels: release-improvements

#484 Fix DWS Calendar Mode Reservations for A3 Mega
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/tests/data/a3_mega.yaml
Labels: release-bugfix

#499 Fix issue in control_plane_endpoints_config.dns_endpoint_config.allow…
  src/xpk/core/cluster.py
Labels: release-bugfix

#494 Fix broken A3 High workloads
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/docker_resources.py
  src/xpk/core/storage.py
  src/xpk/core/workload.py
  src/xpk/core/workload_decorators/tcpx_decorator.py
  src/xpk/templates/rxdm_container_a3high.yaml
  src/xpk/templates/rxdm_container_a3mega.yaml
Labels: release-bugfix

#507 Update PathwaysJob version to v0.1.2
  src/xpk/core/cluster.py
Labels: release-features

#512 Bring back shared_memory volume for A3 Mega and A3 High
  src/xpk/core/workload_decorators/tcpx_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-bugfix
