Repository AI-Hypercomputer/xpk, pull requests merged in 2025-08, with the labels that each got.

#589 Fix cluster create when `--enable-autoprovisioning` is supplied
  src/xpk/core/nap.py
Labels: release-bugfix

#596 Reorder custom_nodepool_arguments for node-pool create command
  src/xpk/core/nodepool.py
Labels: release-bugfix

#602 Fix custom nodepool arguments append
  src/xpk/core/nodepool.py
Labels: release-bugfix

#586 Add tpu7x support
  src/xpk/core/system_characteristics.py
Labels: release-features

#605 Fix provisioning scopes for nap
  src/xpk/core/nap.py
Labels: release-improvements

#607 Update Cluster Toolkit Version to 1.62.2
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/docker_manager.py
  src/xpk/core/tests/data/a3_mega.yaml
  src/xpk/core/tests/data/a3_mega_spot.yaml
  src/xpk/core/tests/data/a3_ultra.yaml
  src/xpk/core/tests/data/a4.yaml
Labels: release-improvements

#613 Release v0.11.0
  .github/CODEOWNERS
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_workload_tests.yaml
  src/xpk/commands/cluster.py
  src/xpk/core/capacity.py
  src/xpk/core/config.py
  src/xpk/core/jobset.py
  src/xpk/core/kueue.py
  src/xpk/core/nap.py
  src/xpk/core/nodepool.py
  src/xpk/core/scheduling.py
  src/xpk/core/system_characteristics.py
  src/xpk/core/tests/unit/test_nodepool.py
Labels: release-features
