Repository AI-Hypercomputer/xpk, pull requests merged in 2025-02, with the labels that each got.

#308 Set up JobSet failure policy on workloads
  README.md
  src/xpk/commands/workload.py
  src/xpk/core/core.py
  src/xpk/core/pathways.py
  src/xpk/parser/workload.py
Labels: release-improvements

#352 Implement config module
  src/xpk/core/config.py
  src/xpk/core/tests/unit/test_config.py
Labels: release-improvements

#360 Fix cluster name when building on develop branch
  .github/workflows/build_tests.yaml
Labels: release-improvements

#361 Fix flaky `Check created job` test
  .github/workflows/build_tests.yaml
Labels: release-bugfix

#359 Add @gcie as codeowner
  .github/CODEOWNERS
Labels: release-improvements

#354 Implement config commands
  pytype-conf.cfg
  src/xpk/commands/config.py
  src/xpk/core/config.py
  src/xpk/core/tests/unit/test_config.py
  src/xpk/parser/config.py
  src/xpk/parser/core.py
Labels: release-features

#370 Merge gcsfuse into develop
  .github/workflows/build_tests.yaml
  .github/workflows/lint_and_format.yml
  .github/workflows/nightly_tests.yaml
  README.md
  docs/contributing.md
  pyproject.toml
  pytype-conf.cfg
  src/xpk/api/__init__.py
  src/xpk/api/storage_crd.yaml
  src/xpk/blueprints/a3mega/storage_crd.yaml
  src/xpk/blueprints/a3ultra/storage_crd.yaml
  src/xpk/commands/cluster.py
  src/xpk/commands/inspector.py
  src/xpk/commands/run.py
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/core.py
  src/xpk/core/nap.py
  src/xpk/core/pathways.py
  src/xpk/core/storage.py
  src/xpk/core/tests/data/a3_mega.yaml
  src/xpk/core/tests/data/a3_ultra.yaml
  src/xpk/core/workload_decorators/rdma_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
  src/xpk/parser/cluster.py
  src/xpk/parser/common.py
  src/xpk/parser/core.py
  src/xpk/parser/storage.py
  src/xpk/parser/workload.py
  src/xpk/templates/__init__.py
  src/xpk/templates/storage.yaml
  src/xpk/utils/kubectl.py
  src/xpk/utils/objects.py
  tests/data/pv-pvc-templates.yaml
Labels: release-features

#374 NCCL tests for A3 ultra
  examples/nccl/nccl.md
  examples/nccl/nccl.sh
Labels: release-improvements

#363 Refactoring - Split core.py into smaller files
  .gitignore
  pytype-conf.cfg
  src/xpk/commands/batch.py
  src/xpk/commands/cluster.py
  src/xpk/commands/cluster_gcluster.py
  src/xpk/commands/common.py
  src/xpk/commands/info.py
  src/xpk/commands/inspector.py
  src/xpk/commands/job.py
  src/xpk/commands/kind.py
  src/xpk/commands/run.py
  src/xpk/commands/storage.py
  src/xpk/commands/version.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/capacity.py
  src/xpk/core/cluster.py
  src/xpk/core/cluster_private.py
  src/xpk/core/config.py
  src/xpk/core/core.py
  src/xpk/core/docker_container.py
  src/xpk/core/docker_image.py
  src/xpk/core/docker_resources.py
  src/xpk/core/gcloud_context.py
  src/xpk/core/kueue.py
  src/xpk/core/monitoring.py
  src/xpk/core/nap.py
  src/xpk/core/network.py
  src/xpk/core/nodepool.py
  src/xpk/core/pathways.py
  src/xpk/core/resources.py
  src/xpk/core/scheduling.py
  src/xpk/core/tests/integration/test_gcluster_a3ultra.py
  src/xpk/core/tests/unit/test_blueprint.py
  src/xpk/core/vertex.py
  src/xpk/core/workload.py
  src/xpk/parser/cluster.py
  src/xpk/parser/config.py
  src/xpk/parser/workload.py
Labels: release-improvements

#366 Implement dependecies validation
  README.md
  pytype-conf.cfg
  src/xpk/commands/version.py
  src/xpk/core/commands.py
  src/xpk/core/config.py
  src/xpk/main.py
  src/xpk/utils/validation.py
Labels: release-improvements

#379 Sync main commits with develop branch
  src/xpk/commands/workload.py
  src/xpk/core/pathways.py
  src/xpk/parser/cluster.py
  src/xpk/parser/workload.py
Labels: release-bugfix

#319 Merge filestore support into develop
  .github/workflows/build_tests.yaml
  .github/workflows/filestore_tests.yaml
  README.md
  examples/storage/filestore-manifest-attach.yaml
  examples/storage/gcsfuse-manifest.yaml
  pyproject.toml
  src/xpk/commands/cluster.py
  src/xpk/commands/cluster_gcluster.py
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/cluster.py
  src/xpk/core/docker_resources.py
  src/xpk/core/filestore.py
  src/xpk/core/storage.py
  src/xpk/core/tests/data/a3_mega.yaml
  src/xpk/core/tests/data/a3_ultra.yaml
  src/xpk/parser/cluster.py
  src/xpk/parser/storage.py
  src/xpk/templates/filestore-pv.yaml
  src/xpk/templates/filestore-pvc.yaml
  src/xpk/templates/filestore-sc.yaml
  tests/data/fs-manifest.yaml
Labels: release-improvements

#382 Fix invalid nvidia libraries mount path for A3 Mega
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-bugfix

#381 Skip Storages if Not Found (instead of failing)
  src/xpk/core/storage.py
Labels: bug, release-bugfix

#383 Refactor storage related decorators to separate file
  src/xpk/commands/workload.py
  src/xpk/core/workload_decorators/rdma_decorator.py
  src/xpk/core/workload_decorators/storage_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-improvements

#385 Update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation, release-improvements

#386 Update Resource Manager Kueue CPU Requirements
  src/xpk/core/pathways.py
Labels: release-bugfix

#392 Fix cluster name when running tests on branch
  .github/workflows/batch_test.yaml
  .github/workflows/build_tests.yaml
  .github/workflows/cluster_create.yaml
  .github/workflows/cluster_delete.yaml
  .github/workflows/cluster_private.yaml
  .github/workflows/filestore_tests.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_format.yml
  .github/workflows/unit_tests.yaml
  .github/workflows/workload_test.yaml
  src/xpk/core/storage.py
Labels: release-improvements

#394 A3 Mega NCCL tests
  examples/nccl/nccl-a3mega.sh
  examples/nccl/nccl-a3ultra.sh
  examples/nccl/nccl.md
Labels: release-improvements

#371 Simplify messages around connecting to Pathways proxy in headless mode.
  src/xpk/commands/workload.py
Labels: release-improvements

#373 Fixes for slurm-like commands
  Makefile
  examples/llama-3.1-finetuning-multi-host/check_cuda.sh
  examples/llama-3.1-finetuning-multi-host/requirements.txt
  examples/llama-3.1-finetuning-multi-host/train-multi-host.slurm
  examples/llama-3.1-finetuning-multi-host/train.py
  examples/llama-3.1-finetuning-multi-host/train.slurm
  examples/llama-3.1-finetuning-multi-host/training_data.jsonl
  examples/llama-3.1-finetuning/check_cuda.sh
  examples/llama-3.1-finetuning/requirements.txt
  examples/llama-3.1-finetuning/train.py
  examples/llama-3.1-finetuning/train.slurm
  examples/llama-3.1-finetuning/training_data.jsonl
  pyproject.toml
  src/xpk/commands/batch.py
  src/xpk/commands/cluster.py
  src/xpk/commands/cluster_gcluster.py
  src/xpk/commands/kind.py
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/commands/storage.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/cluster.py
  src/xpk/core/commands.py
  src/xpk/core/config.py
  src/xpk/core/filestore.py
  src/xpk/core/gcluster_manager.py
  src/xpk/core/kjob.py
  src/xpk/core/remote_state/__init__.py
  src/xpk/core/remote_state/fuse_remote_state.py
  src/xpk/core/remote_state/remote_state_client.py
  src/xpk/core/resources.py
  src/xpk/core/system_characteristics.py
  src/xpk/core/tests/data/a3_ultra.yaml
  src/xpk/core/tests/integration/test_gcluster.py
  src/xpk/core/tests/integration/test_gcluster_a3mega.py
  src/xpk/core/tests/integration/test_gcluster_a3ultra.py
  src/xpk/core/workload.py
  src/xpk/parser/cluster.py
  src/xpk/parser/common.py
  src/xpk/parser/job.py
  src/xpk/parser/shell.py
  src/xpk/utils/gcs_utils.py
Labels: release-improvements, release-bugfix

#377 Implement gcs state bucket parameter passing
  .github/workflows/build_tests.yaml
  .github/workflows/cluster_create.yaml
  .github/workflows/cluster_private.yaml
Labels: release-features

#397 Fixes for slurm like commands
  .github/workflows/batch_test.yaml
  .github/workflows/build_tests.yaml
  .github/workflows/cluster_create.yaml
  .github/workflows/cluster_delete.yaml
  .github/workflows/cluster_private.yaml
  .github/workflows/filestore_tests.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_format.yml
  .github/workflows/nightly_tests.yaml
  .github/workflows/unit_tests.yaml
  .github/workflows/workload_test.yaml
  Makefile
  examples/llama-3.1-finetuning-multi-host/check_cuda.sh
  examples/llama-3.1-finetuning-multi-host/requirements.txt
  examples/llama-3.1-finetuning-multi-host/train-multi-host.slurm
  examples/llama-3.1-finetuning-multi-host/train.py
  examples/llama-3.1-finetuning-multi-host/train.slurm
  examples/llama-3.1-finetuning-multi-host/training_data.jsonl
  examples/llama-3.1-finetuning/check_cuda.sh
  examples/llama-3.1-finetuning/requirements.txt
  examples/llama-3.1-finetuning/train.py
  examples/llama-3.1-finetuning/train.slurm
  examples/llama-3.1-finetuning/training_data.jsonl
  examples/nccl-workload/nccl.md
  examples/nccl-workload/nccl.sh
  src/xpk/commands/batch.py
  src/xpk/commands/cluster.py
  src/xpk/commands/cluster_gcluster.py
  src/xpk/commands/kind.py
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/commands/storage.py
  src/xpk/core/cluster.py
  src/xpk/core/commands.py
  src/xpk/core/config.py
  src/xpk/core/filestore.py
  src/xpk/core/kjob.py
  src/xpk/core/resources.py
  src/xpk/core/system_characteristics.py
  src/xpk/parser/common.py
  src/xpk/parser/job.py
  src/xpk/parser/shell.py
Labels: release-bugfix
