Repository AI-Hypercomputer/xpk, pull requests merged in 2025-03, with the labels that each got.

#399 add troubleshooting section to NCCL test docs
  examples/nccl/nccl.md
Labels: release-improvements

#404 Add environment variables for Pathways metric collection
  src/xpk/commands/workload.py
Labels: release-features

#372 Kjob storage configuration
  .github/workflows/build_tests.yaml
  .github/workflows/filestore_tests.yaml
  .github/workflows/fuse_tests.yaml
  src/xpk/commands/batch.py
  src/xpk/commands/kind.py
  src/xpk/commands/shell.py
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/cluster.py
  src/xpk/core/config.py
  src/xpk/core/kjob.py
  src/xpk/core/pathways.py
  src/xpk/core/storage.py
  src/xpk/core/workload_decorators/storage_decorator.py
  src/xpk/parser/batch.py
  src/xpk/parser/common.py
  src/xpk/parser/shell.py
  src/xpk/parser/storage.py
  src/xpk/templates/volume_bundle.yaml
Labels: release-features

#407 Pin dependency packages versions
  pyproject.toml
Labels: release-improvements

#408 Kjob storage configuration for run command
  .github/workflows/reusable_filestore_tests.yaml
  .github/workflows/reusable_fuse_tests.yaml
  src/xpk/commands/batch.py
  src/xpk/commands/run.py
  src/xpk/commands/shell.py
  src/xpk/commands/storage.py
  src/xpk/commands/workload.py
  src/xpk/core/cluster.py
  src/xpk/core/config.py
  src/xpk/core/kjob.py
  src/xpk/core/pathways.py
  src/xpk/core/storage.py
  src/xpk/core/workload_decorators/storage_decorator.py
  src/xpk/parser/run.py
Labels: release-features

#415 Fix nightly tests
  .github/workflows/nightly_tests.yaml
Labels: release-bugfix

#409 Support for multihost in slurm mode
  examples/llama-3.1-finetuning-multi-host/check_cuda.sh
  examples/llama-3.1-finetuning-multi-host/requirements.txt
  examples/llama-3.1-finetuning-multi-host/train-multi-host.slurm
  examples/llama-3.1-finetuning-multi-host/train.py
  examples/llama-3.1-finetuning-multi-host/train.slurm
  examples/llama-3.1-finetuning-multi-host/training_data.jsonl
  src/xpk/commands/batch.py
  src/xpk/commands/kjob_common.py
  src/xpk/commands/run.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/cluster.py
  src/xpk/core/kjob.py
  src/xpk/core/network.py
  src/xpk/core/workload_decorators/rdma_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-features

#420 `xpk storage detach`
  .github/workflows/reusable_storage_tests_by_type.yaml
  README.md
  src/xpk/commands/storage.py
  src/xpk/core/filestore.py
  src/xpk/parser/storage.py
Labels: release-improvements, release-features

#419 Add job priority support in Slurm mode
  src/xpk/core/kjob.py
  src/xpk/parser/common.py
Labels: release-improvements

#423 Fix xpk version error when cloned from git
  src/xpk/commands/version.py
  src/xpk/core/config.py
Labels: release-bugfix

#426 fix yaml alignment when `remote-python-sidecar-image` is passed
  src/xpk/core/pathways.py
Labels: release-bugfix

#427 Bring back manual manifest specification for attaching storage
  README.md
  src/xpk/commands/storage.py
  src/xpk/parser/storage.py
Labels: release-bugfix

#429 Bump go version to 1.24.1
  tools/Dockerfile-kjob
Labels: release-improvements

#431 Release 0.7.1
  .github/workflows/build_wheels.yaml
  README.md
  pyproject.toml
  src/xpk/commands/storage.py
  src/xpk/core/config.py
  src/xpk/core/pathways.py
  src/xpk/parser/storage.py
  tools/Dockerfile-kjob
Labels: release-improvements, release-bugfix

#432 Release 0.7.1
  .github/workflows/build_wheels.yaml
  README.md
  pyproject.toml
  src/xpk/commands/storage.py
  src/xpk/core/config.py
  src/xpk/core/pathways.py
  src/xpk/parser/storage.py
  tools/Dockerfile-kjob
Labels: release-improvements, release-bugfix

#416 Update cluster-toolkit to 1.47.0
  src/xpk/commands/kjob_common.py
  src/xpk/commands/workload.py
  src/xpk/core/blueprint/blueprint_generator.py
  src/xpk/core/docker_manager.py
  src/xpk/core/kjob.py
  src/xpk/core/tests/data/a3_mega.yaml
  src/xpk/core/tests/data/a3_ultra.yaml
  src/xpk/core/workload_decorators/rdma_decorator.py
  src/xpk/core/workload_decorators/tcpxo_decorator.py
Labels: release-improvements

#435 Remove sudo requirement from make
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_batch_tests.yaml
  .github/workflows/reusable_cluster_create.yaml
  .github/workflows/reusable_cluster_delete.yaml
  .github/workflows/reusable_cluster_private.yaml
  .github/workflows/reusable_integration_tests.yaml
  .github/workflows/reusable_lint_and_format.yml
  .github/workflows/reusable_storage_tests_by_type.yaml
  .github/workflows/reusable_unit_tests.yaml
  .github/workflows/reusable_workload_tests.yaml
  Makefile
Labels: release-bugfix

#437 Release 0.7.2
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_batch_tests.yaml
  .github/workflows/reusable_cluster_create.yaml
  .github/workflows/reusable_cluster_delete.yaml
  .github/workflows/reusable_cluster_private.yaml
  .github/workflows/reusable_integration_tests.yaml
  .github/workflows/reusable_lint_and_format.yml
  .github/workflows/reusable_storage_tests_by_type.yaml
  .github/workflows/reusable_unit_tests.yaml
  .github/workflows/reusable_workload_tests.yaml
  Makefile
  src/xpk/core/config.py
Labels: release-bugfix

#438 Release 0.7.2
  .github/workflows/build_tests.yaml
  .github/workflows/reusable_batch_tests.yaml
  .github/workflows/reusable_cluster_create.yaml
  .github/workflows/reusable_cluster_delete.yaml
  .github/workflows/reusable_cluster_private.yaml
  .github/workflows/reusable_integration_tests.yaml
  .github/workflows/reusable_lint_and_format.yml
  .github/workflows/reusable_storage_tests_by_type.yaml
  .github/workflows/reusable_unit_tests.yaml
  .github/workflows/reusable_workload_tests.yaml
  Makefile
  src/xpk/core/config.py
Labels: release-bugfix
